### ISSUE TITLE
lifecycle-policy file

### ISSUE THREAD

**Issue by Bryan-Meier** [int128/create-ecr-repository-action#1268]
Is it or would it be possible to point to a file in another repo for the lifecycle-policy.json? Our situation is such that we have a repo with our workflow. This workflow is used by multiple other repos by way of workflow_call. Our lifecycle-policy.json file is in the repo that contains our shared workflow and thus we need to point to that file.

Thoughts or ideas are more than welcomed.

**Comment by KelvinVenancio** [comment]
@Bryan-Meier I believe this issue stems more from a limitation with GitHub rather than the action itself. We've encountered a similar situation with our reusable workflows. To address this, we utilize `curl` to fetch the policy file and then configure it across all repositories that implement these workflows. This method ensures consistency and compliance throughout our projects.

```yaml
      - name: Download ECR Policy
        run: |
          curl -s -o lifecycle-policy.json https://pastebin.com/raw/YQxpnEKe

      - uses: int128/create-ecr-repository-action@v1
        with:
          repository: ${{ inputs.ECR_REPO_NAME }}
          lifecycle-policy: lifecycle-policy.json
```

I hope it helps you!
